// =====================================================================
// 🚀 GENERATED CODE - DO NOT MODIFY DIRECTLY
// Generated by custom C++23 Predicate System Generator
// =====================================================================

#pragma once
#include <array>
#include <bitset>
#include <cstdint>
#include <type_traits>
#include <utility>

namespace StuCanvas
{
    // === 1. 严格等差递增的具体类 ID ===
    enum class NodeType : uint32_t
    {
        POINT_2D_FREE = 0,
        POINT_2D_MID,
        POINT_2D_SNAP,
        POINT_2D_SECTION,
        POINT_2D_INTERSECT,
        LINE_2D_SEGMENT,
        LINE_2D_STRAIGHT,
        LINE_2D_RAY,
        LINE_2D_PERPENDICULAR,
        LINE_2D_PARALLEL,
        TANGENT_2D,
        TANGENT_3D,
        CIRCLE_2D,
        CIRCLE_2D_THREE_POINTS,
        ARC_2D,
        ELLIPSE_2D,
        HYPERBOLA_2D,
        PARABOLA_2D,
        POLY_2D_GENERATIVE,
        POINT_3D_FREE,
        POINT_3D_MID,
        POINT_3D_SNAP,
        POINT_3D_SECTION,
        POINT_3D_INTERSECT,
        LINE_3D_SEGMENT,
        LINE_3D_STRAIGHT,
        LINE_3D_RAY,
        LINE_3D_PERPENDICULAR,
        LINE_3D_PARALLEL,
        PLANE_3D,
        PLANE_3D_PARALLEL,
        PLANE_3D_PERPENDICULAR,
        SPHERE_3D,
        SPHERE_3D_FOUR_POINTS,
        CYLINDER_3D,
        CONE_3D,
        CUBOID_3D,
        PLATONIC_SOLID_3D,
        CIRCLE_3D,
        ARC_3D,
        ELLIPSE_3D,
        HYPERBOLA_3D,
        PARABOLA_3D,
        POLY_3D_GENERATIVE,
        SCALAR,
        FUNC_EXPLICIT_2D,
        FUNC_EXPLICIT_3D,
        FUNC_IMPLICIT_2D,
        FUNC_IMPLICIT_3D,
        FUNC_PARAMETRIC_2D,
        FUNC_PARAMETRIC_3D,
        UNKNOWN,
        COUNT
    };

    // === 2. 严格等差递增的特征谓词 ID (从组件依赖中自动动态提取) ===
    enum class NodePredicate : uint32_t
    {
        CATCURVE = 0,
        CATFUNCTION,
        CATLINEAR,
        CATPOINT,
        CATSCALAR,
        CATSURFACE,
        WORLD2D,
        WORLD3D,
        WORLDMETA,
        COUNT
    };

    // === 3. 编译期元数据声明与偏特化 ===
    template < NodeType Tag >
    struct NodeTypeRegistration;

    template <>
    struct NodeTypeRegistration< NodeType::POINT_2D_FREE >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD2D, NodePredicate::CATPOINT };
    };
    template <>
    struct NodeTypeRegistration< NodeType::POINT_2D_MID >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD2D, NodePredicate::CATPOINT };
    };
    template <>
    struct NodeTypeRegistration< NodeType::POINT_2D_SNAP >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD2D, NodePredicate::CATPOINT };
    };
    template <>
    struct NodeTypeRegistration< NodeType::POINT_2D_SECTION >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD2D, NodePredicate::CATPOINT };
    };
    template <>
    struct NodeTypeRegistration< NodeType::POINT_2D_INTERSECT >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD2D, NodePredicate::CATPOINT };
    };
    template <>
    struct NodeTypeRegistration< NodeType::LINE_2D_SEGMENT >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD2D, NodePredicate::CATLINEAR };
    };
    template <>
    struct NodeTypeRegistration< NodeType::LINE_2D_STRAIGHT >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD2D, NodePredicate::CATLINEAR };
    };
    template <>
    struct NodeTypeRegistration< NodeType::LINE_2D_RAY >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD2D, NodePredicate::CATLINEAR };
    };
    template <>
    struct NodeTypeRegistration< NodeType::LINE_2D_PERPENDICULAR >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD2D, NodePredicate::CATLINEAR };
    };
    template <>
    struct NodeTypeRegistration< NodeType::LINE_2D_PARALLEL >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD2D, NodePredicate::CATLINEAR };
    };
    template <>
    struct NodeTypeRegistration< NodeType::TANGENT_2D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD2D, NodePredicate::CATLINEAR,
                                                   NodePredicate::CATCURVE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::TANGENT_3D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATLINEAR,
                                                   NodePredicate::CATCURVE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::CIRCLE_2D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD2D, NodePredicate::CATCURVE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::CIRCLE_2D_THREE_POINTS >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD2D, NodePredicate::CATCURVE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::ARC_2D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD2D, NodePredicate::CATCURVE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::ELLIPSE_2D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD2D, NodePredicate::CATCURVE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::HYPERBOLA_2D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD2D, NodePredicate::CATCURVE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::PARABOLA_2D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD2D, NodePredicate::CATCURVE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::POLY_2D_GENERATIVE >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD2D, NodePredicate::CATLINEAR,
                                                   NodePredicate::CATCURVE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::POINT_3D_FREE >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATPOINT };
    };
    template <>
    struct NodeTypeRegistration< NodeType::POINT_3D_MID >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATPOINT };
    };
    template <>
    struct NodeTypeRegistration< NodeType::POINT_3D_SNAP >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATPOINT };
    };
    template <>
    struct NodeTypeRegistration< NodeType::POINT_3D_SECTION >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATPOINT };
    };
    template <>
    struct NodeTypeRegistration< NodeType::POINT_3D_INTERSECT >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATPOINT };
    };
    template <>
    struct NodeTypeRegistration< NodeType::LINE_3D_SEGMENT >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATLINEAR };
    };
    template <>
    struct NodeTypeRegistration< NodeType::LINE_3D_STRAIGHT >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATLINEAR };
    };
    template <>
    struct NodeTypeRegistration< NodeType::LINE_3D_RAY >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATLINEAR };
    };
    template <>
    struct NodeTypeRegistration< NodeType::LINE_3D_PERPENDICULAR >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATLINEAR };
    };
    template <>
    struct NodeTypeRegistration< NodeType::LINE_3D_PARALLEL >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATLINEAR };
    };
    template <>
    struct NodeTypeRegistration< NodeType::PLANE_3D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATLINEAR,
                                                   NodePredicate::CATSURFACE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::PLANE_3D_PARALLEL >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATLINEAR,
                                                   NodePredicate::CATSURFACE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::PLANE_3D_PERPENDICULAR >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATLINEAR,
                                                   NodePredicate::CATSURFACE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::SPHERE_3D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATSURFACE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::SPHERE_3D_FOUR_POINTS >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATSURFACE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::CYLINDER_3D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATSURFACE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::CONE_3D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATSURFACE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::CUBOID_3D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATSURFACE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::PLATONIC_SOLID_3D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATSURFACE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::CIRCLE_3D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATCURVE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::ARC_3D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATCURVE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::ELLIPSE_3D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATCURVE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::HYPERBOLA_3D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATCURVE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::PARABOLA_3D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATCURVE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::POLY_3D_GENERATIVE >
    {
        static constexpr std::array predicates = { NodePredicate::WORLD3D, NodePredicate::CATLINEAR,
                                                   NodePredicate::CATCURVE };
    };
    template <>
    struct NodeTypeRegistration< NodeType::SCALAR >
    {
        static constexpr std::array predicates = { NodePredicate::WORLDMETA, NodePredicate::CATSCALAR };
    };
    template <>
    struct NodeTypeRegistration< NodeType::FUNC_EXPLICIT_2D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLDMETA, NodePredicate::CATFUNCTION };
    };
    template <>
    struct NodeTypeRegistration< NodeType::FUNC_EXPLICIT_3D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLDMETA, NodePredicate::CATFUNCTION };
    };
    template <>
    struct NodeTypeRegistration< NodeType::FUNC_IMPLICIT_2D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLDMETA, NodePredicate::CATFUNCTION };
    };
    template <>
    struct NodeTypeRegistration< NodeType::FUNC_IMPLICIT_3D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLDMETA, NodePredicate::CATFUNCTION };
    };
    template <>
    struct NodeTypeRegistration< NodeType::FUNC_PARAMETRIC_2D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLDMETA, NodePredicate::CATFUNCTION };
    };
    template <>
    struct NodeTypeRegistration< NodeType::FUNC_PARAMETRIC_3D >
    {
        static constexpr std::array predicates = { NodePredicate::WORLDMETA, NodePredicate::CATFUNCTION };
    };
    template <>
    struct NodeTypeRegistration< NodeType::UNKNOWN >
    {
        static constexpr std::array predicates = { NodePredicate::WORLDMETA, NodePredicate::CATPOINT };
    };

    // === 4. 编译期自动生成的只读二进制位图索引矩阵 ===
    namespace detail
    {
        template < NodeType Tag >
        constexpr bool node_type_has_predicate ( NodePredicate pred )
        {
            for ( auto p : NodeTypeRegistration< Tag >::predicates )
            {
                if ( p == pred )
                {
                    return true;
                }
            }
            return false;
        }

        template < size_t... Is >
        constexpr std::bitset< sizeof...( Is ) > make_node_type_predicate_row ( NodePredicate pred,
                                                                                std::index_sequence< Is... > )
        {
            std::bitset< sizeof...( Is ) > row;
            ( ( row[ Is ] = node_type_has_predicate< static_cast< NodeType > ( Is ) > ( pred ) ), ... );
            return row;
        }

        template < size_t... Is >
        constexpr std::array< std::bitset< static_cast< size_t > ( NodeType::COUNT ) >,
                              static_cast< size_t > ( NodePredicate::COUNT ) >
        make_node_type_bitmap_index ( std::index_sequence< Is... > )
        {
            return { make_node_type_predicate_row (
                static_cast< NodePredicate > ( Is ),
                std::make_index_sequence< static_cast< size_t > ( NodeType::COUNT ) >{} )... };
        }
    }   // namespace detail

    struct alignas ( 64 ) NodeTypeBitmapIndex
    {
        static constexpr auto index_matrix = detail::make_node_type_bitmap_index (
            std::make_index_sequence< static_cast< size_t > ( NodePredicate::COUNT ) >{} );
    };

    // === 5. 纯运行期判定接口：禁止任何模板，禁止编译期计算 ===

    // 判定单个谓词是否拥有
    [[nodiscard]] inline bool has_node_type_predicate ( NodeType type, NodePredicate pred ) noexcept
    {
        const size_t type_idx = static_cast< size_t > ( type );
        const size_t pred_idx = static_cast< size_t > ( pred );

        [[assume ( type_idx < static_cast< size_t > ( NodeType::COUNT ) )]];
        [[assume ( pred_idx < static_cast< size_t > ( NodePredicate::COUNT ) )]];

        return NodeTypeBitmapIndex::index_matrix[ pred_idx ].test ( type_idx );
    }

    // 联合多维谓词聚类判定
    [[nodiscard]] inline bool has_all_node_type_predicates ( NodeType type, const NodePredicate* preds,
                                                             size_t pred_count ) noexcept
    {
        const size_t type_idx = static_cast< size_t > ( type );
        [[assume ( type_idx < static_cast< size_t > ( NodeType::COUNT ) )]];

        for ( size_t i = 0; i < pred_count; ++i )
        {
            const size_t pred_idx = static_cast< size_t > ( preds[ i ] );
            [[assume ( pred_idx < static_cast< size_t > ( NodePredicate::COUNT ) )]];

            if ( !NodeTypeBitmapIndex::index_matrix[ pred_idx ].test ( type_idx ) )
            {
                return false;
            }
        }
        return true;
    }
}   // namespace StuCanvas
