// =====================================================================
// 🚀 GENERATED CODE - DO NOT MODIFY DIRECTLY
// Generated by custom C++23 Predicate System Generator
// =====================================================================

#pragma once
#include <array>
#include <bitset>
#include <cstdint>
#include <type_traits>
#include <utility>

namespace StuCanvas
{
    // === 1. 严格等差递增的具体类 ID ===
    enum class AppearanceType : uint32_t
    {
        SimplePoint = 0,
        SimpleLine,
        OpenPBR,
        OpenPBR_RayTracing,
        COUNT
    };

    // === 2. 严格等差递增的特征谓词 ID (从组件依赖中自动动态提取) ===
    enum class AppearancePredicate : uint32_t
    {
        RayTracing = 0,
        ThreeD,
        TwoD,
        COUNT
    };

    // === 3. 编译期元数据声明与偏特化 ===
    template < AppearanceType Tag >
    struct AppearanceTypeRegistration;

    template <>
    struct AppearanceTypeRegistration< AppearanceType::SimplePoint >
    {
        static constexpr std::array predicates = { AppearancePredicate::TwoD, AppearancePredicate::ThreeD };
    };
    template <>
    struct AppearanceTypeRegistration< AppearanceType::SimpleLine >
    {
        static constexpr std::array predicates = { AppearancePredicate::TwoD, AppearancePredicate::ThreeD };
    };
    template <>
    struct AppearanceTypeRegistration< AppearanceType::OpenPBR >
    {
        static constexpr std::array predicates = { AppearancePredicate::ThreeD };
    };
    template <>
    struct AppearanceTypeRegistration< AppearanceType::OpenPBR_RayTracing >
    {
        static constexpr std::array predicates = { AppearancePredicate::ThreeD, AppearancePredicate::RayTracing };
    };

    // === 4. 编译期自动生成的只读二进制位图索引矩阵 ===
    namespace detail
    {
        template < AppearanceType Tag >
        constexpr bool appearance_type_has_predicate ( AppearancePredicate pred )
        {
            for ( auto p : AppearanceTypeRegistration< Tag >::predicates )
            {
                if ( p == pred )
                {
                    return true;
                }
            }
            return false;
        }

        template < size_t... Is >
        constexpr std::bitset< sizeof...( Is ) > make_appearance_type_predicate_row ( AppearancePredicate pred,
                                                                                      std::index_sequence< Is... > )
        {
            std::bitset< sizeof...( Is ) > row;
            ( ( row[ Is ] = appearance_type_has_predicate< static_cast< AppearanceType > ( Is ) > ( pred ) ), ... );
            return row;
        }

        template < size_t... Is >
        constexpr std::array< std::bitset< static_cast< size_t > ( AppearanceType::COUNT ) >,
                              static_cast< size_t > ( AppearancePredicate::COUNT ) >
        make_appearance_type_bitmap_index ( std::index_sequence< Is... > )
        {
            return { make_appearance_type_predicate_row (
                static_cast< AppearancePredicate > ( Is ),
                std::make_index_sequence< static_cast< size_t > ( AppearanceType::COUNT ) >{} )... };
        }
    }   // namespace detail

    struct alignas ( 64 ) AppearanceTypeBitmapIndex
    {
        static constexpr auto index_matrix = detail::make_appearance_type_bitmap_index (
            std::make_index_sequence< static_cast< size_t > ( AppearancePredicate::COUNT ) >{} );
    };

    // === 5. 纯运行期判定接口：禁止任何模板，禁止编译期计算 ===

    // 判定单个谓词是否拥有
    [[nodiscard]] inline bool has_appearance_type_predicate ( AppearanceType type, AppearancePredicate pred ) noexcept
    {
        const size_t type_idx = static_cast< size_t > ( type );
        const size_t pred_idx = static_cast< size_t > ( pred );

        [[assume ( type_idx < static_cast< size_t > ( AppearanceType::COUNT ) )]];
        [[assume ( pred_idx < static_cast< size_t > ( AppearancePredicate::COUNT ) )]];

        return AppearanceTypeBitmapIndex::index_matrix[ pred_idx ].test ( type_idx );
    }

    // 联合多维谓词聚类判定
    [[nodiscard]] inline bool has_all_appearance_type_predicates ( AppearanceType type,
                                                                   const AppearancePredicate* preds,
                                                                   size_t pred_count ) noexcept
    {
        const size_t type_idx = static_cast< size_t > ( type );
        [[assume ( type_idx < static_cast< size_t > ( AppearanceType::COUNT ) )]];

        for ( size_t i = 0; i < pred_count; ++i )
        {
            const size_t pred_idx = static_cast< size_t > ( preds[ i ] );
            [[assume ( pred_idx < static_cast< size_t > ( AppearancePredicate::COUNT ) )]];

            if ( !AppearanceTypeBitmapIndex::index_matrix[ pred_idx ].test ( type_idx ) )
            {
                return false;
            }
        }
        return true;
    }
}   // namespace StuCanvas
