
// =====================================================================
// 🚀 GENERATED CODE - DO NOT MODIFY DIRECTLY
// Generated by custom C++23 Predicate System Generator
// =====================================================================

#pragma once
#include <cstdint>
#include <array>
#include <bitset>
#include <type_traits>
#include <utility>

namespace StuCanvas
{
    // === 1. 严格等差递增的具体类 ID ===
    enum class CameraType : uint32_t
    {
        Orthographic = 0,
        Perspective,
        COUNT
    };

    // === 2. 严格等差递增的特征谓词 ID (从组件依赖中自动动态提取) ===
    enum class CameraPredicate : uint32_t
    {
        IsLinear = 0,
        IsOrthogonal,
        COUNT
    };

    // === 3. 编译期元数据声明与偏特化 ===
    template < CameraType Tag >
    struct CameraTypeRegistration;

    template <>
    struct CameraTypeRegistration< CameraType::Orthographic >
    {
        static constexpr std::array predicates = { CameraPredicate::IsLinear, CameraPredicate::IsOrthogonal };
    };
    template <>
    struct CameraTypeRegistration< CameraType::Perspective >
    {
        static constexpr std::array predicates = { CameraPredicate::IsLinear };
    };

    // === 4. 编译期自动生成的只读二进制位图索引矩阵 ===
    namespace detail
    {
        template < CameraType Tag >
        constexpr bool camera_type_has_predicate ( CameraPredicate pred )
        {
            for ( auto p : CameraTypeRegistration< Tag >::predicates )
            {               if ( p == pred )
                {
                    return true;
                }
            }
            return false;
        }

        template < size_t... Is >
        constexpr std::bitset< sizeof... ( Is ) > make_camera_type_predicate_row ( CameraPredicate pred, std::index_sequence< Is... > )
        {
            std::bitset< sizeof... ( Is ) > row;
            ( ( row[ Is ] = camera_type_has_predicate< static_cast< CameraType > ( Is ) > ( pred ) ), ... );
            return row;
        }

        template < size_t... Is >
        constexpr std::array< std::bitset< static_cast< size_t > ( CameraType::COUNT ) >, static_cast< size_t > ( CameraPredicate::COUNT ) >
        make_camera_type_bitmap_index ( std::index_sequence< Is... > )
        {
            return {
                make_camera_type_predicate_row ( static_cast< CameraPredicate > ( Is ), std::make_index_sequence< static_cast< size_t > ( CameraType::COUNT ) >{} )...
            };
        }
    }

    struct alignas ( 64 ) CameraTypeBitmapIndex
    {
        static constexpr auto index_matrix = detail::make_camera_type_bitmap_index (
            std::make_index_sequence< static_cast< size_t > ( CameraPredicate::COUNT ) >{}
        );
    };

    // === 5. 纯运行期判定接口：禁止任何模板，禁止编译期计算 ===

    // 判定单个谓词是否拥有
    [[nodiscard]] inline bool has_camera_type_predicate ( CameraType type, CameraPredicate pred ) noexcept
    {
        const size_t type_idx = static_cast< size_t > ( type );
        const size_t pred_idx = static_cast< size_t > ( pred );

        [[assume ( type_idx < static_cast< size_t > ( CameraType::COUNT ) )]];
        [[assume ( pred_idx < static_cast< size_t > ( CameraPredicate::COUNT ) )]];

        return CameraTypeBitmapIndex::index_matrix[ pred_idx ].test ( type_idx );
    }

    // 联合多维谓词聚类判定
    [[nodiscard]] inline bool has_all_camera_type_predicates ( CameraType type, const CameraPredicate* preds, size_t pred_count ) noexcept
    {
        const size_t type_idx = static_cast< size_t > ( type );
        [[assume ( type_idx < static_cast< size_t > ( CameraType::COUNT ) )]];

        for ( size_t i = 0; i < pred_count; ++i )
        {
            const size_t pred_idx = static_cast< size_t > ( preds[ i ] );
            [[assume ( pred_idx < static_cast< size_t > ( CameraPredicate::COUNT ) )]];

            if ( !CameraTypeBitmapIndex::index_matrix[ pred_idx ].test ( type_idx ) )
            {
                return false;
            }
        }
        return true;
    }
} // namespace StuCanvas
